/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'portfolio-videos': PortfolioVideo;
    'contact-submissions': ContactSubmission;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'portfolio-videos': PortfolioVideosSelect<false> | PortfolioVideosSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    home: Home;
    about: About;
    portfolio: Portfolio;
    'contact-page': ContactPage;
    'privacy-page': PrivacyPage;
    'terms-page': TermsPage;
    'services-page': ServicesPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'privacy-page': PrivacyPageSelect<false> | PrivacyPageSelect<true>;
    'terms-page': TermsPageSelect<false> | TermsPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  s3Url?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  category: 'Branding' | 'Web Development' | 'Mobile Apps' | 'UI/UX Design';
  year: string;
  client: string;
  image?: (string | null) | Media;
  tag: string;
  desc: string;
  /**
   * The URL the "Explore Project" button will link to. Leave empty to link to the Contact page.
   */
  projectLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-videos".
 */
export interface PortfolioVideo {
  id: string;
  title: string;
  thumbnail: string | Media;
  videoType: 'file' | 'url';
  videoFile?: (string | null) | Media;
  videoUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  org: string;
  phone: string;
  email: string;
  service: 'web' | 'seo' | 'branding';
  budget: 'sm' | 'md' | 'lg';
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  slug: string;
  shortDescription: string;
  fullDescription: string;
  image: string | Media;
  accent: string;
  tint: string;
  features: {
    feature: string;
    id?: string | null;
  }[];
  overviewImage?: (string | null) | Media;
  workflowSteps?:
    | {
        title: string;
        description: string;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'portfolio-videos';
        value: string | PortfolioVideo;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  s3Url?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  year?: T;
  client?: T;
  image?: T;
  tag?: T;
  desc?: T;
  projectLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-videos_select".
 */
export interface PortfolioVideosSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  videoType?: T;
  videoFile?: T;
  videoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  org?: T;
  phone?: T;
  email?: T;
  service?: T;
  budget?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  fullDescription?: T;
  image?: T;
  accent?: T;
  tint?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  overviewImage?: T;
  workflowSteps?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  navItems: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  callToActionText?: string | null;
  callToActionUrl?: string | null;
  whatsappLogo?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo?: (string | null) | Media;
  description?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  companyLinks: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  bottomLinks: {
    label: string;
    url: string;
    id?: string | null;
  }[];
  socialLinks: {
    platform: string;
    url: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  hero?: {
    subtitle?: string | null;
    title?: string | null;
    images?:
      | {
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    avatars?:
      | {
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
    statsCount?: string | null;
    statsText?: string | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
  };
  stats?: {
    bgImage?: (string | null) | Media;
    items?:
      | {
          number: number;
          suffix?: string | null;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  about?: {
    leftBadge?: {
      percent?: string | null;
      caption?: string | null;
    };
    rightCard?: {
      badge?: string | null;
      title?: string | null;
      description?: string | null;
    };
    carousel?:
      | {
          word1: string;
          word2: string;
          word3: string;
          word4: string;
          image?: (string | null) | Media;
          locationName?: string | null;
          locationRole?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contactBanner?: {
    heading?: string | null;
    subtext?: string | null;
    ctaText?: string | null;
    ctaUrl?: string | null;
  };
  expertise?: {
    eyebrow?: string | null;
    heading?: string | null;
    headingHighlight?: string | null;
    description?: string | null;
    tabs?:
      | {
          tabId: string;
          label: string;
          image?: (string | null) | Media;
          imageAlt?: string | null;
          visualText?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  portfolio?: {
    iconImage?: (string | null) | Media;
    title?: string | null;
    description?: string | null;
    cards?:
      | {
          image?: (string | null) | Media;
          imageAlt?: string | null;
          cardTitle: string;
          cardDesc?: string | null;
          style?: ('clay' | 'blue' | 'white') | null;
          id?: string | null;
        }[]
      | null;
  };
  whyChoose?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          val: string;
          lbl: string;
          icon?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          quote: string;
          name: string;
          role: string;
          id?: string | null;
        }[]
      | null;
  };
  workflow?: {
    title?: string | null;
    tabs?:
      | {
          tabName: string;
          steps?:
            | {
                title: string;
                desc: string;
                image?: (string | null) | Media;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  servicesSection?: {
    eyebrow?: string | null;
    titleLine1?: string | null;
    titleLine2?: string | null;
  };
  faq?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  preFooterCta?: {
    line1?: string | null;
    line2?: string | null;
    line3?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  hero?: {
    title?: string | null;
    tagline?: string | null;
    image?: (string | null) | Media;
    badgeNum?: string | null;
    badgeText?: string | null;
  };
  ticker?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  philosophy?: {
    eyebrow?: string | null;
    title?: string | null;
    cards?:
      | {
          chip: string;
          title: string;
          desc: string;
          id?: string | null;
        }[]
      | null;
  };
  timeline?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          year: string;
          title: string;
          desc: string;
          stats: string;
          chip: string;
          id?: string | null;
        }[]
      | null;
  };
  team?: {
    eyebrow?: string | null;
    title?: string | null;
    members?:
      | {
          image?: (string | null) | Media;
          role: string;
          name: string;
          bio: string;
          id?: string | null;
        }[]
      | null;
  };
  contactCta?: {
    title?: string | null;
    desc?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: string;
  hero?: {
    title1?: string | null;
    title2?: string | null;
    tagline?: string | null;
    image?: (string | null) | Media;
    badgeNum?: string | null;
    badgeText?: string | null;
  };
  zoomSection?: {
    eyebrow?: string | null;
    image?: (string | null) | Media;
    badgeTag?: string | null;
    title?: string | null;
  };
  portfolioStack?: {
    eyebrow?: string | null;
    title?: string | null;
  };
  videoSection?: {
    title?: string | null;
    subtitle?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  heroTitle: string;
  heroTagline: string;
  image?: (string | null) | Media;
  whatsappNumber: string;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  officeHours?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page".
 */
export interface PrivacyPage {
  id: string;
  title: string;
  subtitle: string;
  lastUpdated: string;
  sections?:
    | {
        anchor: string;
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page".
 */
export interface TermsPage {
  id: string;
  title: string;
  subtitle: string;
  effectiveDate: string;
  sections?:
    | {
        anchor: string;
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: string;
  hero: {
    titleLine1: string;
    titleLine2: string;
    tagline: string;
    badgeNumber: string;
    badgeText: string;
  };
  listSection: {
    eyebrow: string;
    title: string;
  };
  processSection: {
    eyebrow: string;
    title: string;
    steps?:
      | {
          stepNumber: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  contactCallout: {
    title: string;
    description: string;
    buttonText: string;
    buttonUrl: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  callToActionText?: T;
  callToActionUrl?: T;
  whatsappLogo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  email?: T;
  phone?: T;
  address?: T;
  companyLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  bottomLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        subtitle?: T;
        title?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        avatars?:
          | T
          | {
              image?: T;
              id?: T;
            };
        statsCount?: T;
        statsText?: T;
        ctaText?: T;
        ctaUrl?: T;
      };
  stats?:
    | T
    | {
        bgImage?: T;
        items?:
          | T
          | {
              number?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        leftBadge?:
          | T
          | {
              percent?: T;
              caption?: T;
            };
        rightCard?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
            };
        carousel?:
          | T
          | {
              word1?: T;
              word2?: T;
              word3?: T;
              word4?: T;
              image?: T;
              locationName?: T;
              locationRole?: T;
              id?: T;
            };
      };
  contactBanner?:
    | T
    | {
        heading?: T;
        subtext?: T;
        ctaText?: T;
        ctaUrl?: T;
      };
  expertise?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingHighlight?: T;
        description?: T;
        tabs?:
          | T
          | {
              tabId?: T;
              label?: T;
              image?: T;
              imageAlt?: T;
              visualText?: T;
              id?: T;
            };
      };
  portfolio?:
    | T
    | {
        iconImage?: T;
        title?: T;
        description?: T;
        cards?:
          | T
          | {
              image?: T;
              imageAlt?: T;
              cardTitle?: T;
              cardDesc?: T;
              style?: T;
              id?: T;
            };
      };
  whyChoose?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              val?: T;
              lbl?: T;
              icon?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              quote?: T;
              name?: T;
              role?: T;
              id?: T;
            };
      };
  workflow?:
    | T
    | {
        title?: T;
        tabs?:
          | T
          | {
              tabName?: T;
              steps?:
                | T
                | {
                    title?: T;
                    desc?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        titleLine1?: T;
        titleLine2?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  preFooterCta?:
    | T
    | {
        line1?: T;
        line2?: T;
        line3?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        tagline?: T;
        image?: T;
        badgeNum?: T;
        badgeText?: T;
      };
  ticker?:
    | T
    | {
        text?: T;
        id?: T;
      };
  philosophy?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        cards?:
          | T
          | {
              chip?: T;
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  timeline?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              year?: T;
              title?: T;
              desc?: T;
              stats?: T;
              chip?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        members?:
          | T
          | {
              image?: T;
              role?: T;
              name?: T;
              bio?: T;
              id?: T;
            };
      };
  contactCta?:
    | T
    | {
        title?: T;
        desc?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title1?: T;
        title2?: T;
        tagline?: T;
        image?: T;
        badgeNum?: T;
        badgeText?: T;
      };
  zoomSection?:
    | T
    | {
        eyebrow?: T;
        image?: T;
        badgeTag?: T;
        title?: T;
      };
  portfolioStack?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  videoSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroTagline?: T;
  image?: T;
  whatsappNumber?: T;
  email?: T;
  phone?: T;
  address?: T;
  officeHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-page_select".
 */
export interface PrivacyPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        anchor?: T;
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-page_select".
 */
export interface TermsPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  effectiveDate?: T;
  sections?:
    | T
    | {
        anchor?: T;
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        titleLine1?: T;
        titleLine2?: T;
        tagline?: T;
        badgeNumber?: T;
        badgeText?: T;
      };
  listSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  processSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              stepNumber?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  contactCallout?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}